Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.network "public_network", ip: "192.168.1.199"
  config.vm.provision "shell", inline: "echo Hello, World >> hello.txt"
end
